name: package2
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  #package3:
  #  path: ../package3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
